"""baseline_m0_through_m4

Revision ID: ef1613187d06
Revises: 
Create Date: 2026-05-28 11:30:03.335915
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'ef1613187d06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_model'), ['model'], unique=False)

    op.create_table('capture_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inbox_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_log_source'), ['source'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_service'), ['service'], unique=False)

    op.create_table('failed_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failed_jobs_service'), ['service'], unique=False)

    op.create_table('inbox_queue',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_queue_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_queue_succeeded'), ['succeeded'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('CONCEPT', 'FACT', 'BUILD', 'PERSON', 'EVENT', 'QUESTION', 'INSIGHT', name='nodetype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('review_questions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('startup_relevance_score', sa.Float(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('obsidian_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_type'), ['type'], unique=False)

    op.create_table('session_state',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('energy_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_strengthened', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edges_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_target_node_id'), ['target_node_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_edges_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_edges_relation_type'))

    op.drop_table('edges')
    op.drop_table('session_state')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_type'))
        batch_op.drop_index(batch_op.f('ix_nodes_title'))

    op.drop_table('nodes')
    with op.batch_alter_table('inbox_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_queue_succeeded'))
        batch_op.drop_index(batch_op.f('ix_inbox_queue_source'))

    op.drop_table('inbox_queue')
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failed_jobs_service'))

    op.drop_table('failed_jobs')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_service'))

    op.drop_table('credentials')
    with op.batch_alter_table('capture_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_log_source'))
        batch_op.drop_index(batch_op.f('ix_capture_log_created_at'))

    op.drop_table('capture_log')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_model'))
        batch_op.drop_index(batch_op.f('ix_api_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_api_usage_agent'))

    op.drop_table('api_usage')
    # ### end Alembic commands ###
