"""Git post-commit hook installer for Synapse.

`synapse hooks install` calls `install_hook()` in the current working
directory.  The generated hook script is pure-stdlib Python so it works on
Windows (Git for Windows / Git Bash), macOS, and Linux without any venv
activation — it only needs a system Python 3.

The script:
    1. Gathers repo name, branch, commit hash, commit message, and diff stats
       via subprocess calls to `git`.
    2. POSTs a JSON payload to `POST /ingest/git` on the local Synapse gateway.
    3. Never fails the commit — all errors are swallowed silently.
"""

from __future__ import annotations

import sys
from pathlib import Path

from synapse.config import GIT_HOOK_DEFAULT_GATEWAY, GIT_HOOK_SCRIPT_NAME

# ── Hook script template ─────────────────────────────────────────────────────
# Uses {{}} for literal braces inside the Python format() call.
# The only substitution is {gateway_url}.

_HOOK_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python3
# Synapse post-commit hook (auto-generated by `synapse hooks install`).
# Edit the GATEWAY_URL line below if your gateway runs on a different port.

import json
import os
import subprocess
import urllib.request

GATEWAY_URL = "{gateway_url}/ingest/git"


def _run(cmd):
    return subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode().strip()


def _numstat():
    \"\"\"Return (files_changed, lines_added, lines_removed) from git numstat.\"\"\"
    files, added, removed = [], 0, 0
    try:
        out = _run(["git", "diff", "--numstat", "HEAD~1", "HEAD"])
    except subprocess.CalledProcessError:
        return files, added, removed  # first commit; no HEAD~1
    for line in out.splitlines():
        parts = line.split("\\t")
        if len(parts) == 3:
            try:
                added += int(parts[0]) if parts[0] != "-" else 0
                removed += int(parts[1]) if parts[1] != "-" else 0
                files.append(parts[2])
            except ValueError:
                pass
    return files, added, removed


def main():
    try:
        repo = os.path.basename(os.getcwd())
        branch = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
        commit_hash = _run(["git", "rev-parse", "HEAD"])
        message = _run(["git", "log", "-1", "--pretty=%B"])
        files_changed, lines_added, lines_removed = _numstat()

        payload = {{
            "repo": repo,
            "repo_path": os.getcwd(),
            "branch": branch,
            "commit_hash": commit_hash,
            "message": message,
            "files_changed": files_changed,
            "lines_added": lines_added,
            "lines_removed": lines_removed,
        }}
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            GATEWAY_URL,
            data=data,
            headers={{"Content-Type": "application/json"}},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=5)
    except Exception:
        pass  # never block a git commit


main()
"""


def install_hook(
    repo_path: Path,
    gateway_url: str = GIT_HOOK_DEFAULT_GATEWAY,
) -> Path:
    """Write `.git/hooks/post-commit` into `repo_path`.

    Creates or replaces the hook script. On POSIX systems the file is made
    executable.  On Windows, Git for Windows executes Python scripts via the
    hashbang without needing the +x bit.

    Args:
        repo_path:   Root directory of the target git repository.
        gateway_url: Base URL of the Synapse gateway (default: localhost:8000).

    Returns:
        Path to the installed hook script.

    Raises:
        ValueError: If `repo_path` is not a git repository (no `.git/` dir).
    """
    git_dir = repo_path / ".git"
    if not git_dir.is_dir():
        raise ValueError(
            f"Not a git repository (no .git/ directory found): {repo_path}"
        )

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    hook_path = hooks_dir / GIT_HOOK_SCRIPT_NAME
    script = _HOOK_SCRIPT_TEMPLATE.format(gateway_url=gateway_url)
    hook_path.write_text(script, encoding="utf-8", newline="\n")

    # Make executable on POSIX (ignored on Windows — Git Bash handles it).
    if sys.platform != "win32":
        hook_path.chmod(0o755)

    return hook_path
